package com.emreilgar.repository.entity;

public enum Department {
    MANAGEMENT_DEPARTMENT,
    LAW_DEPARTMENT,
    HUMAN_RESOURCES_DEPARTMENT,
    ACCOUNTING_DEPARTMENT,
    MARKETING_DEPARTMENT,
    RESEARCH_DEVELOPMENT_DEPARTMENT,
    PRODUCTION_DEPARTMENT,

}
