server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27000
      username: "HRProject-Emre"
      password: "123456789"
      database: Java4UserDb

myapplication:
  userprofile:
    ip: localhost
    port: 9090
  company:
    ip: localhost
    port: 9092
    feignurl: http:///v1/dev/company